### ISSUE TITLE
Unable to parse existing crontab because of leading  space

### ISSUE THREAD

**Issue by salacr** [yzalis/Crontab#26]
Hi

I have crontab which starts with space on every line and due to this it can't be parsed. I fixed that issue locali by changing this in Job.php:

```php
    static function parse($jobLine)
    {
        // split the line
        $parts = explode(' ', $jobLine);
```
to this:
```php
    static function parse($jobLine)
    {
        // split the line
        $parts = explode(' ', trim($jobLine));
```

But' I'm not sure if it's correct aproach

**Comment by blaugueux** [comment]
This can be easily verified by adding a unit test reproducing the bug. Then check if your path make the job.

**Comment by salacr** [comment]
Hi,

It fixes the bug for me, I'm not currently affected by this bug. I'm only letting you know so you can fix it. Or I can create a pull request if you want.

**Comment by blaugueux** [comment]
This will be great if you have time to submit a PR with a fix. I'll be happy to merge it :)

**Comment by salacr** [comment]
Oh,

Now i see that this is already fixed in master. But not in tagged 1.0.3 which I'm using through composer. So this is not a issue right now. Sorry for that.
