### ISSUE TITLE
question: has anyone written a front-end GUI?

### ISSUE THREAD

**Issue by jpuck** [yzalis/Crontab#32]
This is a fabulous library, and I'm curious if there are any front-end implementations out there that I might be able to take a look at?

Thanks,
Jeff P.

**Comment by blaugueux** [comment]
I don't know if a such lib exists. I'm interested or you find something!

**Comment by jpuck** [comment]
@blaugueux thanks for the quick response! I have a request for a simple web app that users can schedule tasks with, and I feel like your lib is perfect, so all that's left is to write an interface.

How do you and others generally use this? Part of console apps only?

**Comment by blaugueux** [comment]
I only use this lib from cli but you can of course create a UI on top of it. 

That's an interesting project 👍
